apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bmac-data-pvc
  namespace: obot-mcp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage

